### ISSUE TITLE
Artwalk error

### ISSUE THREAD

**Issue by Tusgaa** [vgtironi/Discord-Monitor-Bots#2]
Unhandled exception in internal background task 'estoque'.
Traceback (most recent call last):
  File "D:\Área de Trabalho\Pastas\python\lib\site-packages\discord\ext\tasks\__init__.py", line 101, in _loop
    await self.coro(*args, **kwargs)
  File "D:/Área de Trabalho/Pastas/SNKRS/Monitor/Discord-Monitor-Bots-master/ArtwalkMonitor.py", line 134, in estoque
    await channel.send(content=None, embed=embed)
AttributeError: 'NoneType' object has no attribute 'send'

**Comment by gianzin26** [comment]
Quando vc coloca mais de 5 tenis da panilha da Artwalk ele da esse erro
